(function(){
const stories=[
 {title:'El cuaderno olvidado',text:'Cuando llegó a la escuela, Andrés abrió su mochila y descubrió que su cuaderno de matemáticas no estaba. Recordó que la noche anterior había hecho la tarea en la mesa de la cocina. Entonces llamó a su mamá. Ella encontró el cuaderno y se lo llevó antes de comenzar la clase.',qs:[['¿Quién tuvo el problema?',['Andrés','Su mamá'],0],['¿Qué pasó?',['Olvidó su cuaderno','Perdió el autobús'],0],['¿Por qué no estaba en la mochila?',['Porque lo dejó en la cocina','Porque se rompió'],0],['¿Qué quería Andrés al llamar?',['Que buscaran y llevaran el cuaderno','Hablar del recreo'],0],['¿Qué pasó al final?',['Su mamá llevó el cuaderno','Andrés regresó a casa'],0]]},
 {title:'La puerta cerrada',text:'Daniel llegó a casa después de jugar fútbol. Intentó abrir la puerta, pero estaba cerrada. Buscó sus llaves y descubrió que no las tenía. Tocó el timbre varias veces. Su hermana finalmente lo escuchó y abrió la puerta.',qs:[['¿Quiénes participan?',['Daniel y su hermana','Daniel y su profesor'],0],['¿Qué problema tuvo Daniel?',['No podía entrar a casa','No encontraba su pelota'],0],['¿Por qué no podía entrar?',['No tenía llaves','La casa estaba lejos'],0],['¿Qué quería al tocar el timbre?',['Que alguien le abriera','Que alguien saliera a jugar'],0],['¿Qué pasó al final?',['Su hermana abrió','Encontró las llaves en el parque'],0]]}
];
const infer=[
 {text:'Lucía entró corriendo a la casa con el cabello y la ropa mojados. Dejó un paraguas junto a la puerta.',q:'¿Qué podemos inferir?',opts:['Probablemente estaba lloviendo','Probablemente estaba nevando dentro de la casa'],ok:0,clue:'La ropa mojada y el paraguas son pistas.'},
 {text:'El cumpleaños de Camila era al día siguiente. Mateo escondió rápidamente una bolsa cuando ella se acercó.',q:'¿Qué podría intentar hacer Mateo?',opts:['Preparar una sorpresa','Perder la bolsa'],ok:0,clue:'El cumpleaños próximo y esconder la bolsa son pistas.'}
];
const orderItems=[
 ['Tomás pisó un charco y se mojó los zapatos.','Tomás llegó a casa y se quitó los zapatos mojados.','Tomás se puso zapatos secos.'],
 ['Sara abrió su cuaderno para hacer la tarea.','Su lápiz se rompió.','Buscó otro lápiz y continuó.']
];
let si6=0,qi6=0,ii6=0,oi6=0;
function el(tag,attrs={},html=''){const e=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>k==='class'?e.className=v:e.setAttribute(k,v));e.innerHTML=html;return e}
function record(activity,answer,ok=null){if(typeof send==='function')send('answer',activity,answer,ok)}
function addUI(){const daybar=document.querySelector('.daybar');if(!daybar||document.getElementById('day6Btn'))return;const b=el('button',{id:'day6Btn'},'Día 6 · Comprender y contar historias');b.onclick=()=>selectDay(6);daybar.appendChild(b);const block=el('div',{id:'day6Block',class:'hidden'});block.innerHTML=`
<div class="nav"><button onclick="showD6('d6intro')">1. Cinco preguntas</button><button onclick="showD6('d6story')">2. Comprender historia</button><button onclick="showD6('d6cause')">3. Causa e intención</button><button onclick="showD6('d6infer')">4. Inferencias</button><button onclick="showD6('d6order')">5. Ordenar</button><button onclick="showD6('d6problem')">6. Problema y solución</button><button onclick="showD6('d6relevant')">7. Mantener el tema</button><button onclick="showD6('d6personal')">8. Mi historia</button></div>
<section id="d6intro" class="section"><h2>Día 6 · Comprender y contar una historia con orden</h2><p class="small">Para comprender una historia buscamos cinco cosas.</p><div class="three"><div class="stepcard">👤<b>¿QUIÉN?</b><span class="small">Personajes</span></div><div class="stepcard">📖<b>¿QUÉ PASÓ?</b><span class="small">Acontecimiento</span></div><div class="stepcard">💡<b>¿POR QUÉ?</b><span class="small">Causa</span></div><div class="stepcard">🎯<b>¿QUÉ QUERÍA?</b><span class="small">Intención</span></div><div class="stepcard">🏁<b>¿QUÉ PASÓ AL FINAL?</b><span class="small">Resultado</span></div></div><div class="feedback"><b>Estrategia:</b> PERSONA → ACONTECIMIENTO → CAUSA → INTENCIÓN → RESULTADO</div></section>
<section id="d6story" class="section hidden"><h2 id="d6StoryTitle"></h2><div id="d6StoryText" class="story"></div><div id="d6Question" class="feedback"></div><div id="d6StoryChoices" class="choices"></div><div id="d6StoryFb" class="feedback"></div><button class="btn child" onclick="nextD6Question()">Siguiente pregunta</button><button class="btn secondary" onclick="nextD6Story()">Otra historia</button></section>
<section id="d6cause" class="section hidden"><h2>Causa e intención</h2><div class="story">Ana abrió el paraguas porque estaba lloviendo.</div><p><b>¿Cuál es la causa?</b></p><div class="choices"><button class="choice" onclick="d6Cause('Estaba lloviendo',true)">Estaba lloviendo</button><button class="choice" onclick="d6Cause('Quería caminar',false)">Quería caminar</button></div><p><b>¿Cuál es la intención?</b></p><div class="choices"><button class="choice" onclick="d6Intent('No quería mojarse',true)">No quería mojarse</button><button class="choice" onclick="d6Intent('La lluvia empezó ayer',false)">La lluvia empezó ayer</button></div><div id="d6CauseFb" class="feedback">La causa explica por qué ocurrió algo; la intención explica qué quería conseguir la persona.</div></section>
<section id="d6infer" class="section hidden"><h2>Lo que dice y lo que podemos descubrir</h2><div id="d6InferText" class="story"></div><div id="d6InferQ" class="feedback"></div><div id="d6InferChoices" class="choices"></div><div id="d6InferFb" class="feedback"></div><button class="btn child" onclick="nextD6Infer()">Siguiente</button></section>
<section id="d6order" class="section hidden"><h2>Ordenar una historia</h2><p class="small">Toca las partes en el orden en que ocurrieron.</p><div id="d6OrderChoices" class="choices"></div><div id="d6OrderFb" class="feedback">Empieza por lo que ocurrió primero.</div><button class="btn secondary" onclick="resetD6Order()">Reiniciar</button></section>
<section id="d6problem" class="section hidden"><h2>Inicio, problema y solución</h2><div class="story">Sara quería hacer su tarea, pero su lápiz se rompió. Buscó otro lápiz en su mochila y continuó trabajando.</div><div class="grid"><button class="choice" onclick="d6Problem('Inicio','Sara estaba haciendo la tarea',true)"><b>Inicio</b><br>Sara estaba haciendo la tarea</button><button class="choice" onclick="d6Problem('Problema','Se rompió el lápiz',true)"><b>Problema</b><br>Se rompió el lápiz</button><button class="choice" onclick="d6Problem('Solución','Buscó otro lápiz',true)"><b>Solución</b><br>Buscó otro lápiz</button><button class="choice" onclick="d6Problem('Final','Continuó trabajando',true)"><b>Final</b><br>Continuó trabajando</button></div><div id="d6ProblemFb" class="feedback">Una historia suele tener una situación, un problema y una forma de resolverlo.</div></section>
<section id="d6relevant" class="section hidden"><h2>¿Qué información no pertenece?</h2><div class="story">Mario fue a la biblioteca porque necesitaba un libro para su tarea. Buscó en una estantería, pidió ayuda a la bibliotecaria y finalmente encontró el libro. <b>Los elefantes pueden pesar varios miles de kilos.</b> Mario llevó el libro a casa.</div><div class="choices"><button class="choice" onclick="d6Relevant('Los elefantes pueden pesar varios miles de kilos',true)">Los elefantes pueden pesar varios miles de kilos.</button><button class="choice" onclick="d6Relevant('Mario pidió ayuda a la bibliotecaria',false)">Mario pidió ayuda a la bibliotecaria.</button></div><div id="d6RelevantFb" class="feedback">Busca la frase que cambia completamente de tema.</div></section>
<section id="d6personal" class="section hidden"><h2>Mi pequeña historia</h2><div class="grid"><div>¿Quién estaba?<textarea id="d6p1"></textarea></div><div>¿Qué ocurrió?<textarea id="d6p2"></textarea></div><div>¿Por qué ocurrió?<textarea id="d6p3"></textarea></div><div>¿Qué querías tú o la otra persona?<textarea id="d6p4"></textarea></div><div>¿Qué pasó al final?<textarea id="d6p5"></textarea></div><div>Cuéntala completa en orden:<textarea id="d6p6"></textarea></div></div><button class="btn parent" onclick="sendDay6Personal()">Enviar Día 6</button><div id="d6PersonalFb" class="feedback"></div></section>`;const monitor=document.getElementById('monitor');monitor.parentNode.insertBefore(block,monitor);renderD6Story();renderD6Infer();renderD6Order()}
window.showD6=function(id){['d6intro','d6story','d6cause','d6infer','d6order','d6problem','d6relevant','d6personal'].forEach(x=>document.getElementById(x).classList.toggle('hidden',x!==id))};
function renderD6Story(){if(!document.getElementById('d6StoryText'))return;const s=stories[si6],q=s.qs[qi6];d6StoryTitle.textContent=s.title;d6StoryText.textContent=s.text;d6Question.innerHTML='<b>'+q[0]+'</b>';d6StoryChoices.innerHTML=q[1].map((o,i)=>`<button class="choice" onclick="answerD6Story(${i})">${o}</button>`).join('')}
window.answerD6Story=function(i){const s=stories[si6],q=s.qs[qi6],ok=i===q[2];d6StoryFb.textContent=ok?'¡Correcto! Esa respuesta encaja con la historia.':'Revisa las pistas de la historia.';record('Día 6 · Comprensión de historia',{story:s.title,question:q[0],selected:q[1][i],correct:q[1][q[2]]},ok)};
window.nextD6Question=function(){qi6=(qi6+1)%stories[si6].qs.length;renderD6Story()};window.nextD6Story=function(){si6=(si6+1)%stories.length;qi6=0;renderD6Story()};
window.d6Cause=function(a,ok){d6CauseFb.textContent=ok?'Exacto: esa es la causa.':'Eso no explica la causa.';record('Día 6 · Causa',{answer:a},ok)};window.d6Intent=function(a,ok){d6CauseFb.textContent=ok?'Exacto: esa es la intención.':'Eso no describe lo que quería conseguir.';record('Día 6 · Intención',{answer:a},ok)};
function renderD6Infer(){if(!document.getElementById('d6InferText'))return;const x=infer[ii6];d6InferText.textContent=x.text;d6InferQ.innerHTML='<b>'+x.q+'</b>';d6InferChoices.innerHTML=x.opts.map((o,i)=>`<button class="choice" onclick="answerD6Infer(${i})">${o}</button>`).join('')}
window.answerD6Infer=function(i){const x=infer[ii6],ok=i===x.ok;d6InferFb.textContent=ok?'Muy bien. '+x.clue:'Busca las pistas de la historia.';record('Día 6 · Inferencia',{text:x.text,selected:x.opts[i],clue:x.clue},ok)};window.nextD6Infer=function(){ii6=(ii6+1)%infer.length;renderD6Infer()};
let chosen=[];function renderD6Order(){if(!document.getElementById('d6OrderChoices'))return;chosen=[];const arr=orderItems[oi6];const shuffled=[2,0,1];d6OrderChoices.innerHTML=shuffled.map(i=>`<button class="choice" data-i="${i}" onclick="chooseD6Order(this,${i})">${arr[i]}</button>`).join('')}
window.chooseD6Order=function(btn,i){if(chosen.includes(i))return;chosen.push(i);btn.disabled=true;btn.style.opacity=.55;if(chosen.length===3){const ok=chosen.join(',')==='0,1,2';d6OrderFb.textContent=ok?'¡Muy bien! La historia quedó en orden.':'El orden correcto era: primero, después y al final.';record('Día 6 · Ordenar acontecimientos',{selected_order:chosen,correct_order:[0,1,2]},ok)}};window.resetD6Order=function(){oi6=(oi6+1)%orderItems.length;renderD6Order();d6OrderFb.textContent='Empieza por lo que ocurrió primero.'};
window.d6Problem=function(part,a,ok){d6ProblemFb.textContent='Bien: identificaste '+part.toLowerCase()+'.';record('Día 6 · Estructura narrativa',{part,answer:a},ok)};window.d6Relevant=function(a,ok){d6RelevantFb.textContent=ok?'Correcto: esa frase no pertenece al tema de la biblioteca.':'Esa información sí forma parte de la historia.';record('Día 6 · Mantener el tema',{answer:a},ok)};
window.sendDay6Personal=function(){record('Día 6 · Mi historia',{quien:d6p1.value,que:d6p2.value,por_que:d6p3.value,intencion:d6p4.value,final:d6p5.value,historia_completa:d6p6.value});d6PersonalFb.textContent='Historia del Día 6 enviada.'};
const oldSelect=window.selectDay;window.selectDay=function(n){if(n===6){[1,2,3,4,5].forEach(x=>{const bl=document.getElementById('day'+x+'Block'),bt=document.getElementById('day'+x+'Btn');if(bl)bl.classList.add('hidden');if(bt)bt.classList.remove('active')});day6Block.classList.remove('hidden');day6Btn.classList.add('active');record('Día 6 · Navegación',{day:6});}else{if(document.getElementById('day6Block'))day6Block.classList.add('hidden');if(document.getElementById('day6Btn'))day6Btn.classList.remove('active');oldSelect(n)}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addUI);else addUI();
})();