(function(){
const classify=[
 ['Estoy preocupado.','SIENTO'],['Creo que mañana va a llover.','PIENSO'],['Quiero terminar este juego.','QUIERO'],['Necesito un lápiz para hacer la tarea.','NECESITO'],['Pienso que este ejercicio es difícil.','PIENSO'],['Quiero estar solo un momento.','QUIERO']
];
const helpCases=[
 {t:'No puedes abrir un recipiente.',bad:'¡No puedo!',good:'No puedo abrir este recipiente. ¿Me ayudas a abrirlo?'},
 {t:'No entiendes una instrucción.',bad:'No entiendo.',good:'No entendí qué tengo que hacer. ¿Puedes explicármelo otra vez?'},
 {t:'No encuentras tu cuaderno.',bad:'No está.',good:'No encuentro mi cuaderno. ¿Me ayudas a buscarlo?'},
 {t:'Hay demasiado ruido y te cuesta concentrarte.',bad:'Me voy.',good:'Hay mucho ruido y me cuesta concentrarme. Necesito un lugar más tranquilo.'}
];
const rescue=['No sé cómo explicarlo.','Dame un momento para pensarlo.','No entendí la pregunta.','¿Puedes preguntármelo de otra manera?','No recuerdo.','No estoy seguro.'];
let ci7=0,hi7=0;
function el(tag,attrs={},html=''){const e=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>k==='class'?e.className=v:e.setAttribute(k,v));e.innerHTML=html;return e}
function record(activity,answer,ok=null){if(typeof send==='function')send('answer',activity,answer,ok)}
function addUI(){const daybar=document.querySelector('.daybar');if(!daybar||document.getElementById('day7Btn'))return;const b=el('button',{id:'day7Btn'},'Día 7 · Expresar lo que necesito');b.onclick=()=>selectDay(7);daybar.appendChild(b);const block=el('div',{id:'day7Block',class:'hidden'});block.innerHTML=`
<div class="nav"><button onclick="showD7('d7intro')">1. Pienso, siento, quiero, necesito</button><button onclick="showD7('d7classify')">2. Clasificar</button><button onclick="showD7('d7help')">3. Pedir ayuda</button><button onclick="showD7('d7intention')">4. Mi intención</button><button onclick="showD7('d7emotion')">5. Emoción + necesidad</button><button onclick="showD7('d7rescue')">6. Frases de rescate</button><button onclick="showD7('d7personal')">7. Mi mensaje completo</button></div>
<section id="d7intro" class="section"><h2>Día 7 · Expresar lo que pienso, siento, quiero y necesito</h2><p class="small">Los demás no siempre saben lo que estoy pensando. Puedo ayudarlos diciéndolo con palabras.</p><div class="grid"><div class="stepcard">💭<b>PIENSO</b><span class="small">Estoy pensando que...</span></div><div class="stepcard">❤️<b>SIENTO</b><span class="small">Me siento...</span></div><div class="stepcard">⭐<b>QUIERO</b><span class="small">Quiero...</span></div><div class="stepcard">🧰<b>NECESITO</b><span class="small">Necesito...</span></div></div><div class="feedback"><b>Estrategia:</b> PIENSO → SIENTO → QUIERO → DIGO LO QUE NECESITO</div></section>
<section id="d7classify" class="section hidden"><h2>¿Pienso, siento, quiero o necesito?</h2><div id="d7ClassText" class="story"></div><div class="grid"><button class="choice" onclick="answerD7Class('PIENSO')">💭 PIENSO</button><button class="choice" onclick="answerD7Class('SIENTO')">❤️ SIENTO</button><button class="choice" onclick="answerD7Class('QUIERO')">⭐ QUIERO</button><button class="choice" onclick="answerD7Class('NECESITO')">🧰 NECESITO</button></div><div id="d7ClassFb" class="feedback"></div><button class="btn child" onclick="nextD7Class()">Siguiente</button></section>
<section id="d7help" class="section hidden"><h2>Pedir ayuda de forma precisa</h2><div id="d7HelpText" class="story"></div><p><b>¿Cuál mensaje ayuda mejor a la otra persona a entenderte?</b></p><div id="d7HelpChoices" class="choices"></div><div id="d7HelpFb" class="feedback"></div><button class="btn child" onclick="nextD7Help()">Siguiente situación</button></section>
<section id="d7intention" class="section hidden"><h2>¿Qué quiero conseguir?</h2><div class="story">Mario levanta la mano mientras la profesora está hablando.</div><div class="choices"><button class="choice" onclick="d7Intent('Quiere hacer una pregunta o responder',true)">Quiere hacer una pregunta o responder</button><button class="choice" onclick="d7Intent('Quiere esconderse',false)">Quiere esconderse</button></div><div class="story">Sofía se acerca a dos niños que están jugando.</div><div class="choices"><button class="choice" onclick="d7Intent('Podría querer jugar con ellos',true)">Podría querer jugar con ellos</button><button class="choice" onclick="d7Intent('Seguro quiere irse',false)">Seguro quiere irse</button></div><div id="d7IntentFb" class="feedback">La intención explica qué queremos conseguir con una acción.</div></section>
<section id="d7emotion" class="section hidden"><h2>Emoción + causa + necesidad</h2><div class="story">No entiendes una tarea y comienzas a sentir frustración.</div><p>Completa un mensaje claro:</p><div class="grid"><div>Me siento...<textarea id="d7e1" placeholder="Ej.: frustrado"></textarea></div><div>Porque...<textarea id="d7e2" placeholder="Ej.: no entiendo esta parte"></textarea></div><div>Y necesito...<textarea id="d7e3" placeholder="Ej.: que me la expliquen"></textarea></div><div>Mensaje completo:<textarea id="d7e4" placeholder="Me siento... porque... y necesito..."></textarea></div></div><button class="btn parent" onclick="sendD7Emotion()">Enviar respuesta</button><div id="d7EmotionFb" class="feedback"></div></section>
<section id="d7rescue" class="section hidden"><h2>Cuando no sé qué decir</h2><p class="small">También es válido decir que no sabemos o pedir tiempo para responder.</p><div id="d7RescueChoices" class="grid"></div><div id="d7RescueFb" class="feedback">Elige una frase que te pueda ayudar en una conversación.</div></section>
<section id="d7personal" class="section hidden"><h2>Mi mensaje completo</h2><div class="grid"><div>¿Qué está ocurriendo?<textarea id="d7p1"></textarea></div><div>¿Qué pienso?<textarea id="d7p2"></textarea></div><div>¿Qué siento?<textarea id="d7p3"></textarea></div><div>¿Qué quiero?<textarea id="d7p4"></textarea></div><div>¿Qué necesito decir o pedir?<textarea id="d7p5"></textarea></div><div>Escribe el mensaje completo:<textarea id="d7p6"></textarea></div></div><button class="btn parent" onclick="sendDay7Personal()">Enviar Día 7</button><div id="d7PersonalFb" class="feedback"></div></section>`;const monitor=document.getElementById('monitor');monitor.parentNode.insertBefore(block,monitor);renderD7Class();renderD7Help();renderRescue()}
window.showD7=function(id){['d7intro','d7classify','d7help','d7intention','d7emotion','d7rescue','d7personal'].forEach(x=>document.getElementById(x).classList.toggle('hidden',x!==id))};
function renderD7Class(){if(!document.getElementById('d7ClassText'))return;d7ClassText.textContent=classify[ci7][0]}
window.answerD7Class=function(a){const x=classify[ci7],ok=a===x[1];d7ClassFb.textContent=ok?'¡Correcto!':'Aquí corresponde: '+x[1];record('Día 7 · Clasificar mensaje',{statement:x[0],selected:a,correct:x[1]},ok)};window.nextD7Class=function(){ci7=(ci7+1)%classify.length;renderD7Class()};
function renderD7Help(){if(!document.getElementById('d7HelpText'))return;const x=helpCases[hi7];d7HelpText.textContent=x.t;d7HelpChoices.innerHTML=`<button class="choice" onclick="answerD7Help('bad')">${x.bad}</button><button class="choice" onclick="answerD7Help('good')">${x.good}</button>`}
window.answerD7Help=function(which){const x=helpCases[hi7],ok=which==='good';d7HelpFb.textContent=ok?'Muy bien. Ese mensaje explica el problema y lo que necesitas.':'Ese mensaje es demasiado general. Intenta decir exactamente qué necesitas.';record('Día 7 · Pedir ayuda',{situation:x.t,selected:which==='good'?x.good:x.bad,better:x.good},ok)};window.nextD7Help=function(){hi7=(hi7+1)%helpCases.length;renderD7Help()};
window.d7Intent=function(a,ok){d7IntentFb.textContent=ok?'Bien: esa es una intención posible.':'Busca qué podría querer conseguir esa persona.';record('Día 7 · Intención',{answer:a},ok)};
window.sendD7Emotion=function(){record('Día 7 · Emoción y necesidad',{emocion:d7e1.value,causa:d7e2.value,necesidad:d7e3.value,mensaje:d7e4.value});d7EmotionFb.textContent='Mensaje enviado.'};
function renderRescue(){if(!document.getElementById('d7RescueChoices'))return;d7RescueChoices.innerHTML=rescue.map((r,i)=>`<button class="choice" onclick="chooseD7Rescue(${i})">${r}</button>`).join('')}
window.chooseD7Rescue=function(i){d7RescueFb.textContent='Muy bien. Esa frase puede ayudarte cuando no sabes qué responder.';record('Día 7 · Frase de rescate',{selected:rescue[i]})};
window.sendDay7Personal=function(){record('Día 7 · Mi mensaje completo',{situacion:d7p1.value,pensamiento:d7p2.value,emocion:d7p3.value,deseo:d7p4.value,necesidad:d7p5.value,mensaje_completo:d7p6.value});d7PersonalFb.textContent='Respuestas del Día 7 enviadas.'};
const oldSelect=window.selectDay;window.selectDay=function(n){if(n===7){[1,2,3,4,5,6].forEach(x=>{const bl=document.getElementById('day'+x+'Block'),bt=document.getElementById('day'+x+'Btn');if(bl)bl.classList.add('hidden');if(bt)bt.classList.remove('active')});day7Block.classList.remove('hidden');day7Btn.classList.add('active');record('Día 7 · Navegación',{day:7});}else{if(document.getElementById('day7Block'))day7Block.classList.add('hidden');if(document.getElementById('day7Btn'))day7Btn.classList.remove('active');oldSelect(n)}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addUI);else addUI();
})();
